import type { CINotification } from "./types.js";

// ── Shared constants ──────────────────────────────────────────────────────────

/** Default Unix domain socket path for hub↔relay communication. */
export const DEFAULT_HUB_SOCKET = "/tmp/ghci-hub.sock";

/**
 * Routing key extracted from each webhook event.
 * The hub uses this to decide which relays receive a notification.
 */
export interface RoutingKey {
  /** Full repository name: "owner/repo". */
  repo: string;
  /**
   * Branch the event originated from.
   * null means "broadcast to all relays watching this repo".
   */
  branch: string | null;
}

/**
 * Callback type used throughout the webhook pipeline.
 * Both the standalone server and the hub implement this contract so the
 * parsing/debouncing logic in server.ts stays shared and untouched.
 */
export type NotifyFn = (notification: CINotification, routing: RoutingKey) => Promise<void>;

// ── Relay → Hub messages ──────────────────────────────────────────────────────

/** Sent once on connect to declare what this relay wants to receive. */
export interface RegisterMessage {
  type: "register";
  /** Unique ID for this relay (generated by the relay process). */
  relay_id: string;
  /**
   * Repository to watch ("owner/repo").
   * null = wildcard: receive events for every repository.
   */
  repo: string | null;
  /**
   * Branch to watch.
   * null = receive events for every branch in the matched repository.
   */
  branch: string | null;
}

/**
 * Sent when the relay's current git branch changes (detected by polling).
 * The hub updates the relay's routing filter without requiring reconnection.
 */
export interface HeartbeatMessage {
  type: "heartbeat";
  /** New current branch, or null if git detection failed. */
  branch: string | null;
}

export type RelayMessage = RegisterMessage | HeartbeatMessage;

// ── Hub → Relay messages ──────────────────────────────────────────────────────

/** Sent once in response to a successful RegisterMessage. */
export interface RegisteredMessage {
  type: "registered";
  relay_id: string;
}

/** A forwarded CI/PR notification that matched this relay's filters. */
export interface NotifyMessage {
  type: "notify";
  notification: CINotification;
  routing: RoutingKey;
}

/** Keepalive. Relay should respond with a heartbeat within 60 s. */
export interface PingMessage {
  type: "ping";
}

export type HubMessage = RegisteredMessage | NotifyMessage | PingMessage;
